---
colors:
  default: "#ffffff"
  left: "#00ccff"
  left_black: "#0000ff"
  right: "#00ff48"
  right_black: "#00ff00"
  error: "#ff0000"
pixel_count: 175
brightness: 0.15
invert: true
devices:
  piano: Clavinova
  synthesia: Maelstrom
